sudo: false
language: ruby
cache: bundler
env: COVERALLS=true
rvm:
 - 2.2.0
 - 2.2.1
before_script:
 - cp config/database.yml.travis config/database.yml
 - cp config/application.yml.example config/application.yml
 - psql -c 'create database agileista_test;' -U postgres
script:
 - "RAILS_ENV=test bundle exec rake db:migrate 2>&1 >/dev/null"
 - "bundle exec rake db:test:prepare"
 - "bundle exec rspec spec"
services:
 - redis-server
 - elasticsearch
notifications:
  email:
    - lebreeze@gmail.com
